# Generated by Django 6.0.4 on 2026-04-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_alter_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phonenum',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
