# Generated by Django 6.0.4 on 2026-04-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_student_phonenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', to='Core.student'),
        ),
    ]
